# Generated by Django 3.2.25 on 2024-04-18 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_foto_interesse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(blank=True, max_length=30, null=True)),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
                ('endereco', models.CharField(blank=True, max_length=30, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=30, null=True)),
                ('contato', models.CharField(blank=True, max_length=30, null=True)),
                ('historico', models.TextField(blank=True, max_length=500, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
