# Generated by Django 3.2.25 on 2024-04-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('1', 'ONG'), ('2', 'VOLUNTARIO')], max_length=30, null=True),
        ),
    ]
