# Generated by Django 3.2.25 on 2024-04-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.CharField(max_length=100),
        ),
    ]
